name: Run tests with coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate_commit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./test/CrossfireXUnit
      env:
        TESTSETTINGS_JSON: '${{ secrets.TESTSETTINGS_JSON }}'
        SPN_ID: ${{ secrets.SPN_ID }}
        SPN_SECRET: ${{ secrets.SPN_SECRET }}
        TENANT: ${{ secrets.TENANT }}
      run: |
        rm testsettings.json &&
        echo $TESTSETTINGS_JSON > testsettings.json &&
        az login --service-principal --username $SPN_ID --password $SPN_SECRET --tenant $TENANT &&
        dotnet add package coverlet.msbuild &&
        dotnet test CrossfireXUnit.csproj --configuration Debug --runtime linux-x64 /p:CollectCoverage=true /p:CoverletOutput=Coverage/ /p:CoverletOutputFormat=lcov --logger GitHubActions
    - name: Publish Code Coverage
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./test/CrossfireXUnit/TestResults/lcov.info

